= Jenkins pipeline

== Abstract

*Stuck on Jenkins or High on Pipeline?*

In this talk, I will take a critical look at the Jenkins Pipelines.

What is the status of the documentation, what are the nooks and crannies
to get things working, and what is a real PITA to get working.

In the process, the pipeline used for a development pipeline will be demoed, with code samples.


== Related Repositories for Presentation

* https://github.com/JacobAae/greach2017-jenkins-pipeline-demoapp[Demo-app with Jenkinsfile]
* https://github.com/JacobAae/greach2017-jenkins-pipeline-demoapp-integrationtests[Integration tests for demo-app]
* https://github.com/JacobAae/git-remote-add-origin-git-github.com-JacobAae-greach2017-jenkins-pipeline-global-lib[Global library example]


== Links and resources

* https://hub.docker.com/_/jenkins/
* http://blog.alexellis.io/jenkins-2-0-first-impressions/
* https://www.digitalocean.com/community/tutorials/how-to-set-up-a-private-docker-registry-on-ubuntu-14-04
* http://rancher.com/
* http://rancher.com/create-a-private-docker-registry-to-integrate-with-rancher/


== Docker Jenkins

 docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword

TIP: It is not triviel to build and push docker images from a dockerized jenkins

There are docker-compose files for two different configurations of Jenkins,
that will store its configurations between restars in the docker folder
