FROM jenkins:2.32.3

RUN apt-get update && apt-get install -y docker.io && rm -rf /var/lib/apt/lists/*


#COPY plugins.txt /usr/share/jenkins/plugins.txt
#RUN /usr/local/bin/install-plugins.sh /usr/share/jenkins/plugins.txt
