version: '2'

services:
  jenkinsblueocean:
    image: jenkinsci/blueocean
    container_name: jenkins_blueocean
    ports:
      - 8080:8080
    volumes:
      - ./JENKINS-DATA:/var/jenkins_home
      - ../../../demoapp:/tmp/demoapp
      - ../../../demo-integration-tests:/tmp/demo-integration-tests
      - /var/run/docker.sock:/var/run/docker.sock